import { all_routes } from "../../routes/all_routes";

const route = all_routes;
export const getSidebarData = () => {
  const id = sessionStorage.getItem("selectedItems") ?? "";

  return [
  {
    tittle: "Main Menu",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "DashBoard",
        moduleName: "DashBoard",
        parentModuleName: "DashBoard",
        link: route.FinancialDashborad,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-layout-dashboard",
        base: "DashBoard",
        dot: true,
        submenuItems: [
          { label: "Financial", moduleName: "Financial", parentModuleName: "DashBoard", link: route.FinancialDashborad },
          { label: "Material", moduleName: "Material", parentModuleName: "DashBoard", link: route.Material },
        ],
      },
      {
        label: "Masters",
        link: route.FinancialDashborad,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-database",
        base: "Masters",
        dot: true,
        submenuItems: [
          { label: "Source", link: route.SourcesList },
          { label: "Logins", link: route.LoginList },
          { label: "Banks", link: route.BanksList },
          { label: "Materials", link: route.MaterialList },
          { label: "Roles", link: route.Roles}
        ],
      },
      {
        label: id.includes("RMC") ? "Slips" : "Quarry",
        link: route.ContractorList,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-crane", // ✅ valid icon
        base: "Quarry",
        dot: true,
        submenuItems: id.includes("RMC") ? [
          { label: "DC Slips", link: route.DCSlips },
          { label: "Input material", link: route.InputMaterials },
        ] : [
          { label: "Contractor", link: route.ContractorList },
          { label: "Transport", link: route.TransportList },
          { label: "Compressor", link: route.CompresserList },
          { label: "Reports", link: route.ReportList },
          { label: "Contractor Statement", link: route.ContractorStatement },
        ],
      },
      {
        label: "Production",
        link: route.DailyList,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-settings-cog",
        base: "Production",
        dot: true,
        submenuItems: [
          { label: "Daily", link: route.DailyList },
          { label: "Monthly", link: route.MonthlyList },
          { label: "Yearly", link: route.YearlyList },
          { label: "Sales Amount", link: route.SalesAmount },
        ],
      },
      {
        label: "Sales",
        link: route.SalesRegDebitors,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-shopping-cart",
        base: "Sales",
        dot: true,
        submenuItems: [
          { label: "Reg Debitors", link: route.SalesRegDebitors1 },
          // { label: "Reg Debitors 1", link: route.SalesRegDebitors1 },
          { label: "Un-Reg Debitors", link: route.SaleUnRegDebitors },
          { label: "Sales Reports", link: route.SalesReports },
          { label: "Non GST Sales", link: route.NonGstSales },
          { label: "GST Sales", link: route.SaleGstSales },
          { label: "Statement", link: route.SalesStatement },
          { label: "Debitor Report", link: route.SalesDebitorReport },
          { label: "Debitor Summary", link: route.SaleDebitorSummary },
          { label: "Aging", link: route.Aging },
          ...( ["IMIE02062022", "IMIE08042023", "IMIE14072023"].includes(id) ? [{ label: "Other Sales", link: route.OtherSales }] : [] )
        ],
      },
      {
        label: "Yard",
        link: route.ContractorList,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-building-warehouse",
        base: "Yard",
        dot: true,
        submenuItems: [
          { label: "Reports", link: route.YardReports },
          { label: "Stock", link: route.YardStock },
          { label: "Normal Wmt", link: route.YardNormalWmt },
        ],
      },
      {
        label: "Transporter",
        link: route.ContractorList,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-truck",
        base: "Transporter",
        dot: true,
        submenuItems: [
          { label: "Transporter",moduleName:"Transporter" ,link: route.TransPorterList },
          { label: "Vehicle", moduleName: "Vehicle", link: route.TransporterVehicle },
          { label: "Reports",moduleName:"Reports" , link: route.TransPortReports },
          { label: "Statement",moduleName:"Statement",link: route.TransporterStatement },
        ],
      },
      {
        label: "Accounts",
        link: route.ContractorList,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-wallet",
        base: "Accounts",
        dot: true,
        submenuItems: [
          // { label: "Create Groups", link: route.ContractorList },
          { label: "Ledger Creation", link: route.AccountLedgerList },
          { label: "Ledger Type", link: route.AccountLedgerType },
          { label: "Spares Creation",link: route.Spares},
          { label: "Vouchers", link: route.AccountVoucher },
          { label: "Contra", moduleName: "Contra", link: route.AccountContra },
          { label: "Reg Creditors", link: route.AccountRegList },
          { label: "Purchase Bills", link: route.AccountDayBook },
          { label: "Journals", moduleName: "Journals", link: route.AccountJourmal },
          { label: "Cash In (Receipts)", moduleName: "Cash In", link: route.AcccountCashIn },
          { label: "Cash Out (Payments)", moduleName: "Cash Out", link: route.AccountCashOut },
          { label: "Reports", link: route.AccountReports },
          { label: "Recurring", link: route.Recurring },
          {label:"Weigh Bridge ",moduleName:"Weighbridge-Cash", link: route.WeightBridge},
        ],
      },
      {
        label: "Inventory",
        link: route.ContractorList, 
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-packages",
        base: "Inventory",
        dot: true,
        submenuItems: [
          { label: "Issue", link: route.InventoryIssue },
          { label: "Stock", link: route.InventoryStock },
          { label: "Balance", link: route.BalanceList },
        ],
      },
      {
        label: "Diesel",
        link: route.ContractorList,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-gas-station",
        base: "Diesel",
        dot: true,
        submenuItems: [
          { label: "Issue", link: route.DieselIssueList },
          { label: "Reports", link: route.DieselReports },
          { label: "Flow", link: route.DieselFlow },
          { label: "Mileage", link: route.DieselMileage },
        ],
      },
      {
        label: "Vehicle",
        link: route.ContractorList,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-car",
        base: "Vehicle",
        dot: true,
        submenuItems: [
          { label: "Vehicle", link: route.VehicleList },
          { label: "Maintenance", link: route.MaintainanceList },
          { label: "KM Reading", link: route.KMReading },
        ],
      },
      {
        label: "Employee",
        link: route.EmployeeList,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-users",
        base: "Employee",
        dot: true,
        submenuItems: [
          { label: "Employees", link: route.EmployeeList },
          { label: "Attendance", link: route.EmployeeAttendance },
          { label: "Advances", link: route.EmployeeAdvances },
          { label: "Statement", link: route.EmployeeStatement },
          // { label: "Analysis", link: route.EmployeeAnalysis },
        ],
      },
      {
        label: "GST",
        link: route.InvoiceList,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-receipt-tax",
        base: "GST",
        dot: true,
        submenuItems: [
          { label: "Invoice", link: route.InvoiceList },
          { label: "Taxes", link: route.ContractorList },
        ],
      },
      {
        label: "Financial Reports",
        link: route.ContractorList,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-report-money",
        base: "FinancialReports",
        dot: true,
        submenuItems: [
          { label: "Daily Statement", link: route.ContractorList },
          { label: "P/L Statement", link: route.ContractorList },
          { label: "Balance Sheet", link: route.ContractorList },
          { label: "Income Sheet", link: route.IncomeStatement },
        ],
      },
      {
        label: "Misc",
        link: route.MaterialRates,
        submenu: true,
        showSubRoute: false,
        icon: "ti ti-list-details",
        base: "Misc",
        dot: true,
        submenuItems: [
          { label: "Material Rates", link: route.MaterialRates },
        ],
      },
    ]
  }
];
};
